//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDZCSBPingShenXT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_AuditAppear
    {
        public int AuditAppearID { get; set; }
        public string EducationCondition { get; set; }
        public string LanguageCondition { get; set; }
        public string ComputerCondition { get; set; }
        public string SpecialCondition { get; set; }
        public string ProductionFake { get; set; }
        public string AchievementFake { get; set; }
        public string CertificateFake { get; set; }
        public string Other { get; set; }
        public string OtherCause { get; set; }
        public string AuditPass { get; set; }
    }
}
