//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDZCSBPingShenXT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_Basis
    {
        public int BasisID { get; set; }
        public string IdentityCode { get; set; }
        public string TissueOrganization { get; set; }
        public string TissueOrganizationCode { get; set; }
        public Nullable<int> UnitNatureID { get; set; }
        public Nullable<int> BelongIndustryID { get; set; }
        public string Mailbox { get; set; }
        public Nullable<int> DeclareBelongID { get; set; }
        public string StatutoryCall { get; set; }
        public Nullable<int> SubjectionID { get; set; }
        public string ContactPhone { get; set; }
        public string RecordUnit { get; set; }
        public string ExemptCondition { get; set; }
    }
}
