//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDZCSBPingShenXT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_Basic
    {
        public int BasicID { get; set; }
        public Nullable<int> DeclareGradeID { get; set; }
        public Nullable<int> DeclareSeriesID { get; set; }
        public Nullable<int> DeclareQualificationID { get; set; }
        public Nullable<System.DateTime> FormTime { get; set; }
        public Nullable<System.DateTime> TakeOfficeTime { get; set; }
        public string Name { get; set; }
        public Nullable<int> SexID { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string PlaceUnit { get; set; }
        public Nullable<int> EducationID { get; set; }
        public Nullable<int> JudgeEducationID { get; set; }
        public Nullable<int> MajorsPostID { get; set; }
        public Nullable<System.DateTime> GainedQualificationTime { get; set; }
        public Nullable<System.DateTime> EngageTime { get; set; }
        public string EngageYear { get; set; }
        public string TakeOffice { get; set; }
        public string Major { get; set; }
        public string MajorYear { get; set; }
        public Nullable<System.DateTime> JoinWorkTime { get; set; }
        public string ForeignLanguage { get; set; }
        public Nullable<int> ForeignLanguageRankID { get; set; }
        public string ForeignLanguageResult { get; set; }
        public Nullable<int> ExamCaseID { get; set; }
        public Nullable<int> ExamineResultID { get; set; }
        public Nullable<int> ExamineResultID1 { get; set; }
        public Nullable<int> ExamineResultID2 { get; set; }
        public Nullable<int> ExamineResultID3 { get; set; }
        public Nullable<int> ExamineResultID4 { get; set; }
        public Nullable<int> ExamineResultID5 { get; set; }
        public Nullable<int> ExamineResultID6 { get; set; }
        public Nullable<int> DeclareYearID { get; set; }
        public Nullable<int> DeclareYearID1 { get; set; }
        public Nullable<int> DeclareYearID2 { get; set; }
        public Nullable<int> DeclareYearID3 { get; set; }
        public Nullable<int> DeclareYearID4 { get; set; }
        public Nullable<int> DeclareYearID5 { get; set; }
        public byte[] DeclarePicture { get; set; }
        public Nullable<int> DeclareModeID { get; set; }
        public string QuantityScore { get; set; }
        public string ExamResult { get; set; }
        public string ContactPhone { get; set; }
        public Nullable<int> DeclareStatusID { get; set; }
        public Nullable<System.DateTime> GraduateTime { get; set; }
        public Nullable<System.DateTime> GraduateTime1 { get; set; }
        public string GraduateSchool { get; set; }
        public string GraduateSchool1 { get; set; }
        public Nullable<int> MajorID { get; set; }
        public Nullable<int> MajorID1 { get; set; }
    }
}
