//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDZCSBPingShenXT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_DeclarePath
    {
        public int DeclarePathID { get; set; }
        public Nullable<int> DeclareSeriesID { get; set; }
        public Nullable<int> DeclareGradeID { get; set; }
        public Nullable<int> CommittedStateID { get; set; }
        public string ControlUnit { get; set; }
    }
}
