//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDZCSBPingShenXT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_Notice
    {
        public int NoticeID { get; set; }
        public int NoticeTypeID { get; set; }
        public Nullable<int> PromulgatorUnitID { get; set; }
        public string NoticeName { get; set; }
        public string NoticeContent { get; set; }
        public Nullable<System.DateTime> ReleaseTimeStr { get; set; }
        public Nullable<System.DateTime> Effective { get; set; }
        public byte[] Correlation { get; set; }
    }
}
