//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDZCSBPingShenXT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SDZCSBPingShenXTEntities : DbContext
    {
        public SDZCSBPingShenXTEntities()
            : base("name=SDZCSBPingShenXTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<B_Basis> B_Basis { get; set; }
        public virtual DbSet<B_Declare> B_Declare { get; set; }
        public virtual DbSet<B_Experience> B_Experience { get; set; }
        public virtual DbSet<B_WorkResult> B_WorkResult { get; set; }
        public virtual DbSet<S_AchievementGrade> S_AchievementGrade { get; set; }
        public virtual DbSet<S_BelongIndustry> S_BelongIndustry { get; set; }
        public virtual DbSet<S_Category> S_Category { get; set; }
        public virtual DbSet<S_CodeAnswer> S_CodeAnswer { get; set; }
        public virtual DbSet<S_DeclareBelong> S_DeclareBelong { get; set; }
        public virtual DbSet<S_DeclareGrade> S_DeclareGrade { get; set; }
        public virtual DbSet<S_DeclareMode> S_DeclareMode { get; set; }
        public virtual DbSet<S_DeclarePost> S_DeclarePost { get; set; }
        public virtual DbSet<S_DeclareQualification> S_DeclareQualification { get; set; }
        public virtual DbSet<S_DeclareSeries> S_DeclareSeries { get; set; }
        public virtual DbSet<S_DeclareStatus> S_DeclareStatus { get; set; }
        public virtual DbSet<S_DeclareYear> S_DeclareYear { get; set; }
        public virtual DbSet<S_Education> S_Education { get; set; }
        public virtual DbSet<S_ExamCase> S_ExamCase { get; set; }
        public virtual DbSet<S_ExamineResult> S_ExamineResult { get; set; }
        public virtual DbSet<S_ForeignLanguageRank> S_ForeignLanguageRank { get; set; }
        public virtual DbSet<S_MajorsGrade> S_MajorsGrade { get; set; }
        public virtual DbSet<S_MajorsPost> S_MajorsPost { get; set; }
        public virtual DbSet<S_MajorsSeries> S_MajorsSeries { get; set; }
        public virtual DbSet<S_Sortlevel> S_Sortlevel { get; set; }
        public virtual DbSet<S_Subjection> S_Subjection { get; set; }
        public virtual DbSet<S_UnitNature> S_UnitNature { get; set; }
        public virtual DbSet<S_UserRegister> S_UserRegister { get; set; }
        public virtual DbSet<S_UserState> S_UserState { get; set; }
        public virtual DbSet<S_Major> S_Major { get; set; }
        public virtual DbSet<B_Achievement> B_Achievement { get; set; }
        public virtual DbSet<B_Production> B_Production { get; set; }
        public virtual DbSet<S_UnitRegister> S_UnitRegister { get; set; }
        public virtual DbSet<B_Basic> B_Basic { get; set; }
        public virtual DbSet<B_CheckPersonnel> B_CheckPersonnel { get; set; }
        public virtual DbSet<B_Role> B_Role { get; set; }
        public virtual DbSet<S_Sex> S_Sex { get; set; }
        public virtual DbSet<B_WorkPersonnel> B_WorkPersonnel { get; set; }
        public virtual DbSet<B_UnitDeclare> B_UnitDeclare { get; set; }
        public virtual DbSet<B_DeclarePath> B_DeclarePath { get; set; }
        public virtual DbSet<S_CommittedState> S_CommittedState { get; set; }
        public virtual DbSet<B_Audit> B_Audit { get; set; }
        public virtual DbSet<B_AuditAppear> B_AuditAppear { get; set; }
        public virtual DbSet<S_SeriesGrade> S_SeriesGrade { get; set; }
        public virtual DbSet<B_Notice> B_Notice { get; set; }
        public virtual DbSet<S_NoticeType> S_NoticeType { get; set; }
        public virtual DbSet<S_PromulgatorUnit> S_PromulgatorUnit { get; set; }
        public virtual DbSet<B_File> B_File { get; set; }
        public virtual DbSet<S_FileType> S_FileType { get; set; }
    }
}
