//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDZCSBPingShenXT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_UnitRegister
    {
        public int UnitRegisterID { get; set; }
        public string UnitIDCide { get; set; }
        public string RegisterCode { get; set; }
        public string AffirmCode { get; set; }
        public string StatutoryCall { get; set; }
        public string TissueOrganization { get; set; }
        public string TissueOrganizationCode { get; set; }
        public string UseDynamicOrder { get; set; }
        public string DynamicOrderCode { get; set; }
        public string Administrative { get; set; }
        public string CorrespondenceSite { get; set; }
        public string Contact { get; set; }
        public string ContactPhone { get; set; }
        public string MailCode { get; set; }
        public Nullable<int> UnitNatureID { get; set; }
        public Nullable<int> SubjectionID { get; set; }
        public Nullable<int> BelongIndustryID { get; set; }
    }
}
