//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDZCSBPingShenXT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_UserRegister
    {
        public int UserRegisterID { get; set; }
        public string Username { get; set; }
        public string Name { get; set; }
        public Nullable<int> SexID { get; set; }
        public string RegisterCode { get; set; }
        public string AffirmCode { get; set; }
        public string IdentityCode { get; set; }
        public string PhoneCode { get; set; }
        public string Mailbox { get; set; }
        public Nullable<int> AnswerID { get; set; }
        public string CodeAnswer { get; set; }
        public string VerifyCode { get; set; }
    }
}
